# SVM

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('loan_data.csv')

In [2]:
df

Unnamed: 0  credit.policy             purpose  int.rate  installment  \
0              0              1  debt_consolidation    0.1189       829.10   
1              1              1         credit_card    0.1071       228.22   
2              2              1  debt_consolidation    0.1357       366.86   
3              3              1  debt_consolidation    0.1008       162.34   
4              4              1         credit_card    0.1426       102.92   
...          ...            ...                 ...       ...          ...   
9573        9573              0           all_other    0.1461       344.76   
9574        9574              0           all_other    0.1253       257.70   
9575        9575              0  debt_consolidation    0.1071        97.81   
9576        9576              0    home_improvement    0.1600       351.58   
9577        9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 15 columns]

In [3]:
len(df["installment"])

9578

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         9578 non-null   int64  
 1   credit.policy      9578 non-null   int64  
 2   purpose            9578 non-null   object 
 3   int.rate           9578 non-null   float64
 4   installment        9578 non-null   float64
 5   log.annual.inc     9578 non-null   float64
 6   dti                9578 non-null   float64
 7   fico               9578 non-null   int64  
 8   days.with.cr.line  9578 non-null   float64
 9   revol.bal          9578 non-null   int64  
 10  revol.util         9578 non-null   float64
 11  inq.last.6mths     9578 non-null   int64  
 12  delinq.2yrs        9578 non-null   int64  
 13  pub.rec            9578 non-null   int64  
 14  not.fully.paid     9578 non-null   int64  
dtypes: float64(6), int64(8), object(1)
memory usage: 1.1+ MB


In [1]:
df_final = pd.get_dummies(df,drop_first=True)

NameError: name 'pd' is not defined

In [6]:
X = df_final.drop('not.fully.paid',axis=1)
y = df_final['not.fully.paid']

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [8]:
from sklearn.svm import SVC

model = SVC()

model.fit(X_train,y_train)

SVC()

In [9]:
print(y_test)

6170    0
2364    0
7292    0
901     0
4830    1
       ..
8479    0
3861    1
56      0
6147    0
2845    1
Name: not.fully.paid, Length: 2874, dtype: int64


In [15]:
predictions_train = model.predict(X_train)
predictions_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
print(confusion_matrix(y_train,predictions_train))

[[5618    0]
 [1084    2]]


In [17]:
model.score(X_train,y_train)

0.8383054892601431

In [10]:
predictions = model.predict(X_test)
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix

In [12]:
print(confusion_matrix(y_test,predictions))

[[2427    0]
 [ 447    0]]


In [13]:
model.score(X_test,y_test)

0.8444676409185804

In [14]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.84      1.00      0.92      2427
           1       0.00      0.00      0.00       447

    accuracy                           0.84      2874
   macro avg       0.42      0.50      0.46      2874
weighted avg       0.71      0.84      0.77      2874



C:\Users\shail\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\shail\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\shail\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
df_final.columns

Index(['Unnamed: 0', 'credit.policy', 'int.rate', 'installment',
       'log.annual.inc', 'dti', 'fico', 'days.with.cr.line', 'revol.bal',
       'revol.util', 'inq.last.6mths', 'delinq.2yrs', 'pub.rec',
       'not.fully.paid', 'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement',
       'purpose_major_purchase', 'purpose_small_business'],
      dtype='object')

In [44]:
X = df_final[["int.rate","log.annual.inc"]]
y = df_final['not.fully.paid']

In [32]:
X=X.values.reshape(-1,1)

In [45]:
from sklearn.svm import SVC
import numpy as np

model = SVC()

model.fit(X,y)

SVC()

In [34]:
X

array([[0.1189],
       [0.1071],
       [0.1357],
       ...,
       [0.1071],
       [0.16  ],
       [0.1392]])

In [36]:
df

Unnamed: 0  credit.policy             purpose  int.rate  installment  \
0              0              1  debt_consolidation    0.1189       829.10   
1              1              1         credit_card    0.1071       228.22   
2              2              1  debt_consolidation    0.1357       366.86   
3              3              1  debt_consolidation    0.1008       162.34   
4              4              1         credit_card    0.1426       102.92   
...          ...            ...                 ...       ...          ...   
9573        9573              0           all_other    0.1461       344.76   
9574        9574              0           all_other    0.1253       257.70   
9575        9575              0  debt_consolidation    0.1071        97.81   
9576        9576              0    home_improvement    0.1600       351.58   
9577        9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 15 columns]

In [47]:
model.predict([[0.1392,11.264464]])

C:\Users\shail\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0], dtype=int64)