>>># NUMPY

### NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy is an N-dimensional array type called ndarray

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science.

### Using NumPy, a developer can perform the following operations −

Mathematical and logical operations on arrays.

Fourier transforms and routines for shape manipulation.

Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

## Version 


In [4]:
import numpy as np
print(np.__version__)


1.23.3


## Syntax

In [3]:
import numpy as np   # importing numpy module

a = np.array([1,2,3])   # creating numpy 
print(a)

[1 2 3]


## Create a NumPy ndarray Object

#### NumPy is used to work with arrays. The array object in NumPy is called ndarray.
#### We can create a NumPy ndarray object by using the array() function.

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr)) 

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:
# Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


## Dimension

In [8]:
#1-D Arrays

import numpy as np


arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [9]:
#2-D Arrays

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
#3-D arrays

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
#Check dimensions the arrays 
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [13]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Array Indexing

In [14]:
arr = np.array([1, 2, 3, 4])
print(arr[0])


1


In [15]:
arr = np.array([1, 2, 3, 4])
print(arr[1])


2


In [16]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])


7


In [18]:
#2 Dimensional

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print( arr[1,3])

9


In [19]:
#To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])
print(arr[1, 1, 1])


6
11


In [20]:
#Negative Indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -3])

Last element from 2nd dim:  8


In [21]:
#Slicing arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])


[5 6 7]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])


[1 2 3 4]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-4:-2])


[4 5]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:6:2])

[2 4 6]
